#ifndef SPR_COURSE_PROJ_COMMON_CONST_H
#define SPR_COURSE_PROJ_COMMON_CONST_H

#define SERVER_PORT 8090
#define USER_NAME_MAX_LENGTH 24
#define USER_PASS_MAX_LENGTH 32
#define BLACKLIST_ATTEMPTS_THRESHOLD 3
#define NOTIFY_ADMIN_ATTEMPTS_THRESHOLD 2

#define CONNECTION_APPROVED "100"
#define CREDENTIALS_APPROVED "200"
#define ERR_IP_BANNED "403"
#define ERR_INVALID_CREDENTIALS "400"

#endif //SPR_COURSE_PROJ_COMMON_CONST_H
