#ifndef SPR_COURSE_PROJ_SERVER_CONST_H
#define SPR_COURSE_PROJ_SERVER_CONST_H

#define SERVER_MAX_CONN 50
#define USER_CONTAINER_INIT_CAPACITY 10
#define BLACKLIST_INIT_CAPACITY 10

#endif //SPR_COURSE_PROJ_SERVER_CONST_H
